"""enable user address

Revision ID: 00fdded8fed4
Revises:
Create Date: 2022-04-21 11:49:47.979440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00fdded8fed4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("remote_addr", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "remote_addr")
    # ### end Alembic commands ###
