"""password update

Revision ID: dc9d5c6bed53
Revises: 00fdded8fed4
Create Date: 2022-04-23 13:57:07.273581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9d5c6bed53'
down_revision = '00fdded8fed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_update', sa.Float(), default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_update')
    # ### end Alembic commands ###
